name: DynastyProcess.com
title: DynastyProcess.com
description: Finding Method in DynastyFF Madness
show_downloads: false
theme: jekyll-theme-slate
google_analytics: UA-36766776-4
permalink: /:categories/:title/
plugins:
    - jemoji
    - jekyll-feed
authors:
    tan:
        name: Tan Ho
        url: http://www.twitter.com/_TanHo
